ALTER TABLE "academic"."enrollments" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "academic"."students" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "exam"."final_results" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "exam"."marks" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "hostel"."allocations" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "library"."fines" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "library"."issues" ENABLE ROW LEVEL SECURITY;